<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Orders;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $class = null)
    {
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata(Orders::class) : $class);
    }

    /**
     * @param Orders $order
     * @return bool
     */
    public function insertOrder(Orders $order)
    {
        try {
            $this->_em->persist($order);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Orders $orders
     * @return bool
     */
    public function deleteOrder(Orders $orders)
    {
        try {
            $this->_em->remove($orders);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Orders $orders
     * @return bool
     */
    public function updateOrder(Orders $orders)
    {
        try {
            $this->_em->merge($orders);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
