<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use AppBundle\Entity\Category;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\ORMException;
use Doctrine\ORM\TransactionRequiredException;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * CategoryRepository constructor.
     * @param EntityManagerInterface $em
     * @param Mapping\ClassMetadata $class
     */
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $class = null)
    {
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata(Product::class) : $class);
    }

    /**
     * @param int $id
     * @return Product|null
     */
    public function getOneById(int $id): ?Product
    {
        try {
            return $this->_em->find('AppBundle:Product', $id);
        } catch (OptimisticLockException $e) {
            return null;
        } catch (TransactionRequiredException $e) {
            return null;
        } catch (ORMException $e) {
            return null;
        }
    }

    /**
     * @param Product $article
     * @return bool
     */
    public function insert(Product $article): bool
    {
        try {
            $this->_em->persist($article);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Product $article
     * @return bool
     */
    public function update(Product $article): bool
    {
        try {
            $this->_em->merge($article);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Product $article
     * @return bool
     */
    public function delete(Product $article): bool
    {
        try {
            $this->_em->remove($article);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

}
