<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Promotion;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * PromotionRepository constructor.
     * @param EntityManagerInterface $em
     * @param Mapping\ClassMetadata|null $class
     */
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $class = null)
    {
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata(Promotion::class) : $class);
    }

    /**
     * @param Promotion $promotion
     * @return bool
     */
    public function insert(Promotion $promotion) {
        try {
            $this->_em->persist($promotion);
            $this->_em->flush($promotion);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Promotion $promotion
     * @return bool
     */
    public function update(Promotion $promotion) {
        try {
            $this->_em->merge($promotion);
            $this->_em->flush($promotion);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Promotion $promotion
     * @return bool
     */
    public function delete(Promotion $promotion) {
        try {
            $this->_em->remove($promotion);
            $this->_em->flush($promotion);
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

}
