<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Specification;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * SpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * SpecificationRepository constructor.
     * @param EntityManagerInterface $em
     * @param Mapping\ClassMetadata|null $class
     */
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $class = null)
    {
        parent::__construct($em, $class == null ? new Mapping\ClassMetadata(Specification::class) : $class);
    }

    /**
     * @param Specification $specification
     * @return bool
     */
    public function insert(Specification $specification)
    {
        try {
            $this->_em->persist($specification);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Specification $specification
     * @return bool
     */
    public function update(Specification $specification)
    {
        try {
            $this->_em->merge($specification);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Specification $specification
     * @return bool
     */
    public function delete(Specification $specification)
    {
        try {
            $this->_em->remove($specification);
            $this->_em->flush();

            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
